export enum Game {
  SEVEN_DAYS_TO_DIE = "SEVEN_DAYS_TO_DIE",
  ARK_SURVIVAL_EVOLVED = "ARK_SURVIVAL_EVOLVED",
  DAYZ = "DAYZ",
  MINECRAFT = "MINECRAFT",
  PALWORLD = "PALWORLD",
  ARMA_REFORGER = "ARMA_REFORGER",
  RUST = "RUST",
  SCUM = "SCUM",
  VALHEIM = "VALHEIM",
}
